apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sa-en
  labels:
    app.kubernetes.io/name: service-sa-en
    app.kubernetes.io/component: web
  namespace: rabbits
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-sa-en
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-sa-en
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: service-sa-uk
          image: artem1sobolev/service-sa-en:1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq-creds

